name: SignIt
main: Wertzui123\SignIt\Main
version: 3.1
api: 4.0.0
load: POSTWORLD
author: Wertzui123
description: Sign items on a text
website: https://github.com/Wertzui123/SignIt
permissions:
 signit.command.sign:
  default: op
  description: Lets you use /signit
 signit.cooldown.bypass:
  default: op
  description: Lets you bypass the cooldown