name: SignIt
main: Wertzui123\SignIt\Main
version: 2.0
api: 3.0.0
load: POSTWORLD
author: Wertzui123
description: Sign items with /signit on a text!
website: https://discord.gg/XXkZGsP
permissions:
 signit:
  default: op
  description: Lets you use all features of SignIt
  children:
   signit.command:
    children:
     signit.command.sign:
      default: true
      description: Lets you use /signit
   signit.wait.bypass:
    default: op
    description: Lets you bypass the waiting time