---
# Don't edit this if you don't know what you're doing
config-version: 3.1

# Configuration for all commands registered by SignIt
command:
  # The /sign command
  sign:
    command: "sign"
    description: "Sign the item in your hand on a given text"
    usage: "/sign <text: string>"
    aliases: []

# Multiple permission groups can be set up to allow certain players to have shorter cooldowns
# If a player has the permission for multiple permission groups, the first group in the list will be their permission group
# 'default' is the default permission group
permission_groups:
  - vip # players need the permission signit.permissions.vip to have the cooldown from this group

# The time players have to wait between signing items
# The time is in seconds
# 86400 seconds is one day
# Each permission group has its own waiting time
cooldown:
  default: 86400
  vip: 43200

# This is the format how the sign will be shown
# {player} is the name of the player who signed the item
# {text} the text the player signed on the item
# {date} is the date at which day the player signed the item
# {group} or {rank} is the player's PurePerms group
sign_format: "§r§d({date}) §b{player}: \n§r§f{text}"
time_format: 'd.m.Y H:i'

# If true, the old sign on an item will be replaced with the new one when signing an item
# If false, signs will stack
# Warning: this will not work for items that have been signed before setting this to true
overrideOldSign: false
...