---
version: 2.0

# COMMAND
command: 'signit'
description: 'Let you sign items'
aliases: ['sign']

# In minutes
wait_time: 1440
lore_timeformat: 'm.d.Y H:i'

# This is the format how the sign will be shown
# {date} is the date at wich day the player signed (date can be adjusted at "lore_timeformat")
# {player} is the name of the player who signed the item
# {text} the text the player signed on the item
# {group} or {rank} is the players pureperms group
sign_format: "§r§d({date}) §b{player}: \n§r§f{text}"
...