---
run_in_game: "§cPlease run this command in-game!"
usage: "§cUsage: /signit <message>"
please_hold_an_item: "§l§bSign §7> §r§aPlease hold an item in you're hand, wich can be signed!"
signed_as: "rrr"
sign_succes: "§l§bSign §7> §r§aYou have succesfully singed the item in you're hand to §6{signedas}§a!"
missing_permission: "§cYou don't have the permission to sign items with /signit!"
//This Plugin was written by Wertzui123 and you're not allowed to modify or rewrite it!
//To adjust it, just use the config.yml in the plugin_data/SignIt folder.
//© 2019 Wertzui123
...
